### ISSUE TITLE
Feature: TransformCastSchema need check load_can_auto_cast_to during construction

### ISSUE THREAD

**Issue by sundy-li** [databendlabs/databend#16790]
**Summary**

Description for this feature.

**Comment by youngsofun** [comment]
`load_can_auto_cast_to` is much more strict, only used for load, not suitable for here.

we may introduce another help function like https://github.com/databendlabs/databend/pull/16072
this closed pr was intended to be used in copy only too (replaced by `load_can_auto_cast_to`  later)

but @andylokandy  said 

```
理论上 任何类型都可以互转
所以之前没有 can_cast_to ，cast 不过去是值的问题不是类型问题
```

I think since currently our cast (run_cast) do report error on some (src, dst) pairs.
may be it is ok to add a `can_cast_to` which is consistent with `run_cast` to report error earlier when building pipeline,
and check it when constructing TransformCastSchema

**Comment by sundy-li** [comment]
But `run_cast` will check the cast types and throw 

```
  _ => Err(ErrorCode::BadArguments(format!(
                "unable to cast type `{src_type}` to type `{dest_type}`"
            ))
            .set_span(span)),
```

**Comment by andylokandy** [comment]
We can say a value is not able to cast to other type, e.g. `CAST('a' AS INT), but we can not say all `String` can not be cast to `Int`. The former will throw at evaluation, and the latter will throw at type checking.

**Comment by sundy-li** [comment]
> The former will throw at evaluation, and the latter will throw at type checking.

The latter will not throw errors at type checking, let's add it.

It will always return `Expr::Cast`
```
fn check_cast<Index: ColumnIndex> ... {

 Ok(Expr::Cast {
            span,
            is_try,
            expr: Box::new(expr),
            dest_type: wrapped_dest_type,
        })
}

```

**Comment by sundy-li** [comment]
A simple case, the error is thrown during sql pipeline execution.
```
🐳 :) create table a (t decimal(15,2));
processed in (0.018 sec)


🐳 :) insert into a select * from b;
error: APIError: ResponseError with 1006: fail to auto cast column t (Variant NULL) to column t (Decimal(15, 2) NULL)
unable to cast type `Variant` to type `Decimal(15, 2)`, during run expr: `CAST(t AS Decimal(15, 2) NULL)`

```

**Comment by andylokandy** [comment]
> The former will throw at evaluation, and the latter will throw at type checking.

I mean, if we agree that all types can convert between each other, i.e. 
`We can say that a value is not able to be cast to another type, e.g. CAST('a' AS INT), but we can not say that all String can not be cast to Int`.， we should not throw at type checking.
