### ISSUE TITLE
Add test: MetaAPI: add table operation on absent db.

### ISSUE THREAD

**Issue by drmingdrmer** [databendlabs/databend#4098]
A `UnknownDatabase` error is expected.

`common/meta/api/src/meta_api_test_suite.rs`

**Comment by ClSlaid** [comment]
BTW, I found a strange `-`(`u+2010` instead of `u+002d`) in this [line](https://github.com/datafuselabs/databend/blob/cb1557caca976ae10d55ef848275b5540daf609d/common/meta/api/src/meta_api_test_suite.rs#L637), is this intention?
![图片](https://user-images.githubusercontent.com/44747719/154252146-f6ee84b8-ac2f-461b-ac69-1a54efaa3056.png)

**Comment by drmingdrmer** [comment]
Good catch!
Of cause not intentional. :DDD
